### ISSUE TITLE
How does admixr calculate stats for populations (multiple individuals belonging to same group)?

### ISSUE THREAD

**Issue by jychoilab** [bodkan/admixr#71]
Hi

Very sorry for a question like this but could you clarify how for instance for d() is calculating D-statistics when the .ind file contain populations (groups of individuals with the same population classification) and not a single individual per population classification?

Thank you

**Comment by bodkan** [comment]
Hi,

f-statistics (and by extension also D statistics) work with allele frequencies. So there's really no difference in how the statistics are calculated in these two cases, a single individual can be understood simply as population of size one - with possible allele frequencies 0, 0.5 or 1.

For details about the theoretical properties of these statistics and methods how they are calculated I recommend reading papers by [Patterson et al.](https://www.genetics.org/content/192/3/1065) and [Peter](https://www.genetics.org/content/202/4/1485).

I will close this issue now because this is not really a bug report. If you'd like to discuss the theoretical properties of f-statistics, I recommend contacting the authors.

Hope this helps!
