### ISSUE TITLE
custom jackknife 

### ISSUE THREAD

**Issue by nicolo-tellini** [bodkan/admixr#83]
Hello @bodkan,

I was wondering if custom block sizes or number of blocks can be specified for the jackknife approach an why by default the package use 0.05, moreover are these Morgan/centiMorgan ?

Thank you for your time,

Best regards

Nicolò

**Comment by bodkan** [comment]
Hi,

Any ADMIXTOOLS parameter can be changed via the `params =` argument of each _admixr_ function. For an example see [here](https://github.com/bodkan/admixr/issues/76#issuecomment-704224526) and the [manual page](https://bodkan.net/admixr/reference/f4ratio.html) of this package.

The default value is 0.05 simply because this is the hardcoded default value [in ADMIXTOOLS itself](https://github.com/DReichLab/AdmixTools/search?q=blgsize). The search result in this link also searched through their documentation (or, rather, README files) which explains what the `blgsize` parameter exactly is (and that the units are in centimorgans).

**Comment by bodkan** [comment]
Given that this doesn't seem to involve a bug in _admixr_ and that I'm fairly confident it has the same solutions as the [previously answered](https://github.com/bodkan/admixr/issues?q=is%3Aissue+params+is%3Aclosed) similar issues, I will close this. Feel free to re-open if you find that the solution doesn't work.

**Comment by nicolo-tellini** [comment]
Hello Martin,

Thank you very much for your fast reply!

Best regards,

Nicolò

**Comment by bodkan** [comment]
Happy to help. 👍

Good luck with your work and if you find that admixr helped you, please consider citing it in your paper(s)! 😉
